### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by HarshadRanganathan** [HarshadRanganathan/helm-aws-istio-service-mesh#1]
- [ ] Discovery Selectors -> Limit services tracked by Istio Control Plane
- [ ] Define default route rules in Virtual Service -> Destination Rule traffic policies are not applied if no specific route rules exist for that subset from virtual service
- [ ] Destination Rule lookup path -> installing in service namespace vs different namespace
- [ ] Virtual Service & Destination Rule fragments -> Host merging of multiple configuration files
- [ ] Service Route configuration order

When adding new subsets:

- Update DestinationRules to add a new subset first, before updating any VirtualServices that use it. Apply the rule using kubectl or any platform-specific tooling.
- Wait a few seconds for the DestinationRule configuration to propagate to the Envoy sidecars
- Update the VirtualService to refer to the newly added subsets.

When removing subsets:

- Update VirtualServices to remove any references to a subset, before removing the subset from a DestinationRule.
- Wait a few seconds for the VirtualService configuration to propagate to the Envoy sidecars.
- Update the DestinationRule to remove the unused subsets.

- [ ] Bound only specific domains to gateways

```
servers:
- port:
    number: 80
    name: http
    protocol: HTTP
  hosts:
  - "foo.example.com" # Allow only VirtualServices that are for foo.example.com
  - "default/bar.example.com" # Allow only VirtualServices in the default namespace that are for bar.example.com
  - "route-namespace/*" # Allow only VirtualServices in the route-namespace namespace for any host
```

- [ ] Dedicated vs Shared Gateway
- [ ] Explicit protocol selection (https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/#explicit-protocol-selection)
- [ ] Prometheus recording rules (https://istio.io/latest/docs/ops/best-practices/observability/)
- [ ] Use `app` and `version` labels
- [ ] Named service ports -> helps with protocol selection
